# File: src/main/resources/application-dev.yml
"%dev":
  quarkus:
    redis:
      hosts:
        - ${COM_SM_REDIS_HOST:redis://localhost}:${COM_HC_REDIS_PORT:6379}
      password: ${COM_SM_SERVER_BFF_REDIS_PASSWORD:}
      database: ${COM_SM_SERVER_BFF_REDIS_DATABASE:1}

    datasource:
      db-kind: ${COM_SM_DATABASE_DB_KIND:mysql}
      jdbc:
        url: ${COM_SM_DATABASE_URL:mysql://localhost:3307/thecoffeebox}
        driver: ${COM_SM_DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
        username: ${COM_SM_DATABASE_USERNAME:root}
        password: ${COM_SM_DATABASE_PASSWORD:root}
      devservices:
        enabled: false
    hibernate-orm:
      database:
        generation: drop-and-create

    log:
      console:
        enable: true
      level: INFO
