# File: src/main/resources/application-dev.yml
"%dev":
  quarkus:
    redis:
      hosts:
        - redis://${COM_SM_REDIS_HOST:localhost}:${COM_HC_REDIS_PORT:6379}/${COM_SM_SERVER_REDIS_DATABASE:1}
      password: ${COM_SM_SERVER_REDIS_PASSWORD:}
#    kafka:
#      # ceres.thecoffeebox.vn:9092
#      bootstrap-servers: ${COM_HC_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#      devservices:
#        enabled: ${COM_SM_DEVSERVICES_ENABLED:false}

    datasource:
      db-kind: ${COM_SM_DATABASE_DB_KIND:mysql}
      reactive:
        url: ${COM_SM_DATABASE_URL}
        driver: ${COM_SM_DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
      username: ${COM_SM_DATABASE_USERNAME:root}
      password: ${COM_SM_DATABASE_PASSWORD:root}
      devservices:
        enabled: ${COM_SM_DEVSERVICES_ENABLED:false}
    hibernate-orm:
      database:
        generation: ${COM_SM_DATABASE_GENERATION:none}
      log:
        sql: ${COM_SM_LOG_SQL:false}
        format-sql: ${COM_SM_LOG_FORMAT_SQL:false}

    log:
      console:
        enable: ${COM_SM_LOG_CONSOLE_ENABLE:true}
      level: ${COM_SM_LOG_LEVEL:INFO}
