# File: src/main/resources/application-dev.yml
"%dev":
  quarkus:
    redis:
      hosts:
        - redis://${COM_SM_REDIS_HOST:localhost}:${COM_HC_REDIS_PORT:6379}/${COM_SM_SERVER_BFF_REDIS_DATABASE:1}
      password: ${COM_SM_SERVER_BFF_REDIS_PASSWORD:}

    datasource:
      db-kind: ${COM_SM_DATABASE_DB_KIND:mysql}
      reactive:
        url: ${COM_SM_DATABASE_URL:mysql://localhost:3307/socialmedia}
        driver: ${COM_SM_DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
      username: ${COM_SM_DATABASE_USERNAME:root}
      password: ${COM_SM_DATABASE_PASSWORD:root}
      devservices:
        enabled: false
    hibernate-orm:
      database:
        generation: drop-and-create

    log:
      console:
        enable: true
      level: INFO
